openapi: 3.0.3
info:
  title: Customer API
  description: API specification for Customer entity
  version: 1.0.0

components:
  schemas:
    Customer:
      type: object
      required:
        - id
        - name
        - email
      properties:
        id:
          type: string
          description: Unique customer identifier
          example: "cust-12345"
        name:
          type: string
          description: Customer full name
          minLength: 1
          maxLength: 100
          example: "John Doe"
        email:
          type: string
          format: email
          description: Customer email address
          example: "john.doe@example.com"
        phone:
          type: string
          pattern: "^\\+?[1-9]\\d{1,14}$"
          description: Customer phone number (E.164 format)
          example: "+1234567890"
        dateOfBirth:
          type: string
          format: date
          description: Customer date of birth
          example: "1990-01-15"
        address:
          $ref: '#/components/schemas/Address'
        status:
          type: string
          enum: ["active", "inactive", "suspended"]
          description: Customer account status
          default: "active"
        createdAt:
          type: string
          format: date-time
          description: Account creation timestamp
          readOnly: true
        updatedAt:
          type: string
          format: date-time
          description: Last update timestamp
          readOnly: true

    Address:
      type: object
      required:
        - street
        - city
        - country
      properties:
        street:
          type: string
          description: Street address
          example: "123 Main St"
        city:
          type: string
          description: City name
          example: "New York"
        state:
          type: string
          description: State or province
          example: "NY"
        postalCode:
          type: string
          description: Postal or ZIP code
          example: "10001"
        country:
          type: string
          description: Country code (ISO 3166-1 alpha-2)
          pattern: "^[A-Z]{2}$"
          example: "US"

paths:
  /customers:
    post:
      operationId: customersPost
      summary: Create a new customer
      x-process-id: process-entity-demo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '201':
          description: Customer created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
