openapi: 3.0.3
info:
  title: Missing Name Test API
  description: API specification for testing missing entity name scenarios
  version: 1.0.0

components:
  schemas:
    Customer:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          description: Unique customer identifier
          example: "cust-12345"
        name:
          type: string
          description: Customer name
          example: "Test User"

paths:
  /customers:
    get:
      summary: Get customer data
      responses:
        '200':
          description: Customer data retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
